name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: ashutoshvarma/action-cmake-build@master
    - name: cmake
      run: cmake .
    - name: make
      run: make
